name: 'Branch Set up and AWS Auth'
description: 'Composite steps to set branch and auth into AWS'

inputs:
  aws_region:
    description: 'AWS region to configure'
    required: true
  aws_oidc_assume_role:
    description: 'The OIDC role to assume'
    required: true
  branch:
    description: 'branch reference'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
          
    - name: Write branch name to a file
      run: echo ${{ inputs.branch }} > BRANCH
      shell: bash
      
    - name: Archive branch name file
      uses: actions/upload-artifact@v3
      with:
        name: branch
        path: BRANCH
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_oidc_assume_role }}