name: 'Composite Setup'
description: 'Checkout and configure AWS credentials'

inputs:
  ref:
    description: 'Git ref to checkout'
    required: true
  aws-region:
    description: 'AWS region for configuration'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
    - name: config aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}
