name: 'Reusable Workflow Steps'
description: 'Composite steps for setting up environment and preparing build artifacts'

inputs:
  workflow_file:
    description: 'Name of the workflow file to download artifacts from'
    required: true
  artifact_name:
    description: 'Name of the artifact to download'
    required: true
  artifact_path:
    description: 'Path to download the artifact to'
    required: true
  aws_region:
    description: 'AWS region for the configured credentials'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  aws_oidc_assume_role:
    description: 'AWS access OIDC'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Plan Artifact
      id: download_artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow_file }}
        name: ${{ inputs.artifact_name }}
        workflow_conclusion: success
        github_token: ${{ inputs.github_token }}
        path: ${{ inputs.artifact_path }}

    - name: Setup Environment Variables
      id: setup_env
      run: echo "BRANCH=$(cat ${{ inputs.artifact_path }}/${{ inputs.artifact_path }})" >> $GITHUB_ENV
      shell: bash

    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH }}

    - name: Configure AWS Credentials
      id: aws_creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_oidc_assume_role }}
        aws-region: ${{ inputs.aws_region }}

    - name: Set Up TF 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    
